env: sleuth-dev
server:
  port: 7002
spring:
  application:
    name: sleuth-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://cks:8761/eureka/,http://cks1:8762/eureka/
#  instance:
#      prefer-ip-address: true