eureka:
  client:
    serviceUrl:
      defaultZone: http://cks:8761/eureka/,http://cks1:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    common:
      path: /common/**
      serviceId: common
    user:
      path: /user/**
      serviceId: user
  host:
      max-total-connections: 10000
      max-per-route-connections: 50
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
              timeoutInMilliseconds: 41000