server:
  port: 8989
security:
  basic:
    enabled: false  #开启基于HTTP basic的认证
  user:
    name: admin    #配置登陆名
    password: 123456   #配置登陆密码
spring:
  application:
    name: hystirx-turbine
management:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://cks1:8762/eureka/
#turbine:
#  app-config: common
#  cluster-name-expression: "'default'"
#  combine-host-port: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: user,common
  clusterNameExpression: new String("default")